### ISSUE TITLE
Make the cursor position track the selected error

### ISSUE THREAD

**Issue by floli** [yasuyk/helm-flycheck#8]
When you are traversing the list of errors/warnings make the point in the source buffer follow the currently highlighted error. (optionally)

On closing the helm-flycheck buffer, return the point to the position it was when helm-flycheck was called. When selecting a error using RET, move point to the selected error and close the buffer (like it currently is).

Thanks!

**Comment by yasuyk** [comment]
@floli Done. This feature is developed by @wh11e7rue at #9.
